const top100Films = [
  "Fiction",
  "Science Fiction",
  "Fantasy",
  "Thriller",
  "Mystery",
  "Romance",
  "Historical Fiction",
  "Non-fiction",
  "Biography",
  "Self-help",
  "Cookbooks",
  "Children's Books",
  "Young Adult",
  "Graphic Novels",
  "Literary Fiction",
  "Classics",
  "True Crime",
  "Poetry",
  "Health & Wellness",
  "Business & Economics",
  "Art & Photography",
  "Mindfulness & Meditation",
  "Politics & Government",
  "Religion & Spirituality",
  "Environmentalism",
  "Memoir",
];
export default top100Films;
